import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import { GeistSans } from 'geist/font/sans'



import "./globals.css";

const noto_sans_jp = Noto_Sans_JP({ weight: "400", subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "AureliusAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        {children}
      </body>
    </html>
  );
}
